### ISSUE TITLE
Problem Saving MCMC output

### ISSUE THREAD

**Issue by ppernot** [tlafarge/NICOB_app_public#1]
Hi, 

I am trying to save the MCMC output from a run of the Bayesian model (example = pcb),
but the click on the button returns either "An error has occured" or the home page of the app. 

Thanks

**Comment by tlafarge** [comment]
Could you please send me your ncb file? You can save it on the main page of
the app.

**Comment by ppernot** [comment]
Here it is... Sorry, I cannot attach it: the extension is not allowed by github :-(

```
NICOB version=1.4
lablabels=IRMM, KRISS, NARL, NIST, NMIJ, NRC
mean=34.30, 32.90, 34.53, 32.42, 31.90, 35.80
se=1.03, 0.69, 0.83, 0.29, 0.40, 0.38
df=60, 4, 18, 2, 13, 60
units=
coverage=0.95
DoE=FALSE
signifDigits=2
bootrep=NA
nburnin_lap=50000
linearOPrep=100000
knhacheck=FALSE
seed=5
DoEbootrep=10000
nburnin=50000
niters_lap=250000
nthin_lap=25
niters=250000
doboot=FALSE
nthin=25
LOODoE=FALSE
poolweights=
```

**Comment by aakoepke** [comment]
Thanks for pointing out this issue! I've fixed the problem in the server.R code.

**Comment by ppernot** [comment]
OK, thanks !

When will it be propagated to the CONSENSUS web app ?

**Comment by dnewton600** [comment]
We'll send the updated version to our Linux admin today, so hopefully the web version will be updated within the next several days. I'll reply here to confirm.
